[Variables]

cont_nowplaying_1    = Now
cont_nowplaying_2    = playing
cont_previous        = Previous
cont_play            = Play
cont_pause           = Pause
cont_next            = Next
cont_fetching        = Fetching...

act_open_settings    = Open Settings panel
act_use_regular      = Use regular Cleartext
act_use_pure         = Use Cleartext Pure

set_settings         = Settings
set_settings_abbv    = Settings
set_updates          = Updates
set_installed        = Installed
set_uptodate         = You're currently up-to-date.

set_tit_align_text       = Align text
set_tit_change_fonts     = Change fonts
set_tit_change_media     = Change media player
set_tit_resize           = Resize Cleartext
set_tit_stow             = Stow controls
set_tit_switch_color     = Switch colors
set_tit_switch_bottom    = Switch bottom text
set_tit_switch_top       = Switch top text
set_tit_toggle_hide      = Toggle Adaptive Hide
set_tit_toggle_pure      = Toggle between Pure
set_tit_toggle_scroll    = Toggle scroll
set_tit_trim             = Trim text

set_btn_done         = Done
set_btn_reset        = Reset
set_btn_help         = Help
set_btn_left         = Left
set_btn_right        = Right
set_btn_enable       = Enable
set_btn_disable      = Disable
set_btn_black        = Black
set_btn_white        = White
set_btn_size         = Now at
set_btn_font_thin    = Thin font here
set_btn_font_thick   = Thick font here
set_btn_font_ctrl    = Controls font here
set_btn_name_artist  = Artist name
set_btn_name_album   = Album name
set_btn_name_title   = Song title

set_tip_help         = Get help -- read the support documentation (internet connection required)
set_tip_close        = Close Settings
set_tip_done         = Refreshing will take effect once this button is pressed.
set_tip_reset        = Refreshing will take effect once the Done button is pressed.

set_stat_left        = left
set_stat_right       = right
set_stat_enabled     = enabled
set_stat_disabled    = disabled

set_desc_align_text      = Align Cleartext to the left or right to match its position on your screen. It is currently on the
set_desc_change_fonts    = Change the fonts used in Cleartext and Cleartext Pure with fonts installed in your PC. Enter the font name as displayed by Windows.
set_desc_change_media    = Currently set player
set_desc_resize          = Enter the height of Cleartext in pixels. Width and contents will adjust accordingly. Press the Enter key when finished inputting the desired height.
set_desc_stow            = Hide \"Now Playing\" and the progress bar on normal state to show only track information. It is currently 
set_desc_switch_color    = Choose the color of Cleartext that contrasts with your current wallpaper.
set_desc_switch_bottom   = Choose which part of the track information to show in the bottom text.
set_desc_switch_top      = Choose which part of the track information to show in the top text.
set_desc_toggle_hide_1   = Adaptive Hide allows Cleartext to hide when music is stopped in
set_desc_toggle_hide_2   = It is currently
set_desc_toggle_scroll   = Toggle the scrolling text on Cleartext Pure. It is currently enabled
set_desc_trim            = Trim the text on the title, artist, and album name by removing extra characters. This only works for English songs. It is currently