[Variables]

cont_nowplaying_1    = 
cont_nowplaying_2    = 
cont_previous
cont_play
cont_pause
cont_next
cont_fetching

act_open_settings
act_use_regular
act_use_pure

set_settings
set_settings_abbv
set_updates
set_installed
set_uptodate

set_tit_align_text
set_tit_change_fonts
set_tit_change_media
set_tit_resize
set_tit_stow
set_tit_switch_color
set_tit_switch_bottom
set_tit_switch_top
set_tit_toggle_hide
set_tit_toggle_pure
set_tit_toggle_scroll
set_tit_trim

set_btn_done
set_btn_reset
set_btn_help
set_btn_left
set_btn_right
set_btn_enable
set_btn_disable
set_btn_black
set_btn_white
set_btn_size            =
set_btn_font_thin
set_btn_font_thick
set_btn_font_ctrl
set_btn_name_artist
set_btn_name_album
set_btn_name_title

set_tip_help
set_tip_close
set_tip_progress_bar
set_tip_done         =
set_tip_reset        =

set_stat_left
set_stat_right
set_stat_enabled
set_stat_disabled

set_desc_align_text
set_desc_align_text_2 =
set_desc_change_fonts
set_desc_change_media
set_desc_resize
set_desc_stow
set_desc_switch_color
set_desc_switch_bottom
set_desc_switch_top
set_desc_toggle_hide_1   = 
set_desc_toggle_hide_2   = 
set_desc_toggle_scroll
set_desc_trim