[Variables]

; --- PROGRESS BAR
orientation_progressbar=Vertical
width_progressbar=2.7
height_progressbar=135
xpos_progressbar=118.8
ypos_progressbar=16.2

; --- NOW
xpos_now=108
ypos_now=59.4

; --- PLAYING
xpos_playing=108
ypos_playing=78.3

; --- NOW PLAYING FOR CENTER
xpos_nowplaying=372.6
ypos_nowplaying=24.3

; --- UPDATE INDICATOR
xpos_indicator=37.8
ypos_indicator=63.45

; --- TIME
xpos_time=108
ypos_time=18.9

; --- SETTINGS
xpos_settings=67.5
ypos_settings=35.1

; --- PLAY BUTTON
xpos_play=64.8
ypos_play=126.9

; --- PREVIOUS BUTTON
xpos_prev=108
ypos_prev=108

; --- NEXT BUTTON
xpos_next=108
ypos_next=126.9

; --- INTERFACE
align_interface=Right

; --- REGULAR: CONTAINERS
xpos_container_reg=132.3
ypos_containertop_reg=29.7
ypos_containerbtm_reg=76.95
width_container_reg=587.25

; --- STANDARD: CONTAINERS
width_container_std=587.25
width_container_scroll=691.2
height_container_std=59.4

; --- CONTAINER TEXT
xpos_containertext=0
ypos_containertextbtm=0
ypos_containertexttop=64.8
align_containertext_supposed=Left

; PURE --------------

; --- PURE, UPDATE INDICATOR
pure_xpos_indicator=0

; --- PURE, REGULAR: CONTAINERS
pure_ypos_containertop_reg=24.3
pure_ypos_containerbtm_reg=71.55
