[Variables]

; --- PROGRESS BAR
orientation_progressbar=Horizontal
width_progressbar=(#skinSize#+(#skinSize#*0.33))
height_progressbar=(#skinSize#*0.005)
xpos_progressbar=(#skinSize#*0.01)
ypos_progressbar=(#skinSize#*0.11)

; --- NOW
xpos_now=(#skinSize#*0.65)
ypos_now=(#skinSize#*0.06)

; --- PLAYING
xpos_playing=(#skinSize#*0.835)
ypos_playing=(#skinSize#*0.06)

; --- TIME
xpos_time=(#skinSize#*0.5)
ypos_time=(#skinSize#*0.07)

; --- PROGRESS
xpos_progress=(#skinSize#*1.04)
ypos_progress=(#skinSize#*0.07)

; --- SETTINGS
xpos_settings=(#skinSize#*0.965)
ypos_settings=(#skinSize#*0.07)

; --- PLAY BUTTON
xpos_play=(#skinSize#*0.725)
ypos_play=(#skinSize#*0.02)

; --- PREVIOUS BUTTON
xpos_prev=(#skinSize#*0.575)
ypos_prev=(#skinSize#*0.02)

; --- NEXT BUTTON
xpos_next=(#skinSize#*0.845)
ypos_next=(#skinSize#*0.02)

; --- INTERFACE
align_interface=Center

; --- REGULAR: CONTAINERS
xpos_container_reg=(#skinSize#*0.0275)
ypos_container_reg=(#skinSize#*0.13)
width_container_reg=(#skinSize#+(#skinSize#*0.3))

; --- STANDARD: CONTAINERS
width_container_std=(#skinSize#+(#skinSize#*0.09))
width_container_scroll=(#skinSize#+(#skinSize#*0.3))
height_container_std=(#skinSize#*0.0825)

xpos_containertext=(#skinSize#*0.67)
align_containertext_supposed=Center