[Variables]

; --- PROGRESS BAR
orientation_progressbar=Horizontal
width_progressbar=594
height_progressbar=2.7
xpos_progressbar=75.6
ypos_progressbar=58.05

; --- NOW
xpos_now=325.35
ypos_now=24.3

; --- PLAYING
xpos_playing=403.11
ypos_playing=24.57

; --- NOW PLAYING FOR CENTER
xpos_nowplaying=372.6
ypos_nowplaying=24.3

; --- UPDATE INDICATOR
xpos_indicator=453.6
ypos_indicator=30.78

; --- TIME
xpos_time=243
ypos_time=29.7

; --- PROGRESS
xpos_progress=550.8
ypos_progress=29.7

; --- SETTINGS
xpos_settings=499.5
ypos_settings=29.7

; --- PLAY BUTTON
xpos_play=391.5
ypos_play=0

; --- PREVIOUS BUTTON
xpos_prev=310.5
ypos_prev=0

; --- NEXT BUTTON
xpos_next=450.9
ypos_next=0

; --- INTERFACE
align_interface=Center

; --- REGULAR: CONTAINERS
xpos_container_reg=14.31
ypos_containertop_reg=56.7
ypos_containerbtm_reg=103.95
width_container_reg=702

; --- STANDARD: CONTAINERS
width_container_std=587.25
width_container_scroll=712.8
height_container_std=59.4

; --- CONTAINER TEXT
xpos_containertext=356.4
ypos_containertextbtm=0
ypos_containertexttop=64.8
align_containertext_supposed=Center

; PURE --------------

; --- PURE, UPDATE INDICATOR
pure_xpos_indicator=372.6

; --- PURE, REGULAR: CONTAINERS
pure_ypos_containertop_reg=24.3
pure_ypos_containerbtm_reg=71.55
bool_alignright=0
bool_aligncenter=1
