[Variables]

; --- SIZES (Backwards-compatible)

skinSize=(#SCREENAREAHEIGHT#*0.5)
lastSetWidth=525

; --- TEXT CUSTOMIZATIONS

font_weightbtm=700
font_texttop=Red Hat Display
font_textbtm=Red Hat Display
font_textinterface=Red Hat Text Medium

; --- INTERNAL SWITCHES AND CONFIGURATIONS

bool_alignright=0
bool_aligncenter=0
bool_adaptivehide=0
bool_stow=0
bool_texttrim=0

; --- ACTIVE LOW SWITCHES AND CONFIGURATIONS

bool_scroll=0

; --- NAMING

name_stowgroup=NULL
name_toptext=mArtist
name_bottomText=mTitle

; --- INTERNAL PLAYER CONTROLS

;; 0 = Music, 1 = GPMDP, 2 = WebNowPlaying
player_mode=0
player_supposed=Spotify

player_controller=Title0

player_setname=Spotify (NowPlaying)
player_setvalue=WMP

; --- DYNAMIC DISABLE (Active low switches)
disable_np=0
disable_gpmdp=1
disable_wnp=1
color_btn_adaptivehide_sint=128,128,128,255
bool_btn_adaptivehide_sint=off
