[Variables]

name_lastgroup_sint=g_update

; --- ADAPTIVE HIDE
color_btn_adaptivehide_sint=128,128,128,255
bool_btn_adaptivehide_sint=off

; --- SCROLLING
color_btn_scrolling_sint=255,179,41,255
bool_btn_scrolling_sint=on

; --- STOW
color_btn_stow_sint=128,128,128,255
bool_btn_stow_sint=off

; --- TRIM TEXT
color_btn_trim_sint=128,128,128,255
bool_btn_trim_sint=off

; --- PLAYER

color_btn_aimp_sint=128,128,128,255
color_btn_foobar2000_sint=128,128,128,255
color_btn_gpmdp_sint=128,128,128,255
color_btn_itunes_sint=128,128,128,255
color_btn_jrmc_sint=128,128,128,255
color_btn_mediamonkey_sint=128,128,128,255
color_btn_mpc_sint=128,128,128,255
color_btn_musicbee_sint=128,128,128,255
color_btn_spotify_sint=255,179,41,255
color_btn_vlc_sint=128,128,128,255
color_btn_winamp_sint=128,128,128,255
color_btn_wmp_sint=128,128,128,255
color_btn_wnp_sint=128,128,128,255
color_btn_zune_sint=128,128,128,255
