[Variables]

skinSize=(#SCREENAREAHEIGHT#*0.5)
bottomTextWidth=596


Player=Spotify
alignRight=1

activePlugin=NowPlaying


; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=2
playerController=StateButton2
currentlySetName=WebNowPlaying
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=540
mediaTextAlignment=RightBottom
mediaTextAlignmentPure=Right
interfaceTextAlignment=Left
nowTextPositionHor=677
hairlinePositionHor=660.8
topTextPositionHor=644.6
playCtrlPositionHor=722.9
settingsTextPositionHor=717.5
indicatorPositionHor=739.1
indicatorPositionHorPure=523.8
conflictIndicatorPositionHor=709.4
conflictIndicatorPositionHorPure=502.2
