[Variables]

skinSize=(#SCREENAREAHEIGHT#*0.5)
lastSetWidth=674

Player=Spotify
alignRight=1

activePlugin=NowPlaying

topTextWidth=344
bottomTextWidth=674

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=2
playerController=StateButton2
currentlySetName=WebNowPlaying
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=540
mediaTextAlignment=RightBottom
mediaTextAlignmentPure=Right
interfaceTextAlignment=Left
nowTextPositionHor=755
hairlinePositionHor=738.8
topTextPositionHor=722.6
playCtrlPositionHor=800.9
settingsTextPositionHor=795.5
indicatorPositionHor=817.1
indicatorPositionHorPure=523.8
conflictIndicatorPositionHor=787.4
conflictIndicatorPositionHorPure=502.2
