[Variables]

skinSize=(#SCREENAREAHEIGHT#*0.5)

topTextWidth=513
bottomTextWidth=739
lastSetWidth=739

Player=Spotify
alignRight=1

activePlugin=NowPlaying


; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=2
playerController=StateButton2
currentlySetName=WebNowPlaying
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=540
mediaTextAlignment=RightBottom
mediaTextAlignmentPure=Right
interfaceTextAlignment=Left
nowTextPositionHor=820
hairlinePositionHor=803.8
topTextPositionHor=787.6
playCtrlPositionHor=865.9
settingsTextPositionHor=860.5
indicatorPositionHor=882.1
indicatorPositionHorPure=523.8
conflictIndicatorPositionHor=852.4
conflictIndicatorPositionHorPure=502.2
